apiVersion: instance.cow.network/v1
kind: Instance
metadata:
  name: test
spec:
  template:
    containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.9
        ports:
          - containerPort: 8080
